# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        #AppBundle\Entity\Compte:
         #   algorithm: bcrypt
          #  cost: 12
        # Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\Compte: sha512
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        pere_provider:
            entity:
                class: AppBundle:Compte
                #property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            http_basic: ~
            provider: pere_provider
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                #use_referer: true
            logout:
                path:   /logout
                target: /
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN}
        - { path: ^/compte, roles: ROLE_USER}
        - { path: ^/payment/, roles: ROLE_USER, requires_channel: https }
        - { path: ^/Choix_Paiement, roles: ROLE_USER} #, requires_channel: https }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY} #, requires_channel: https }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER,ROLE_ANNONCE]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_AGENT,ROLE_ANNONCE]